//! Float conversions with the exact semantics of the Python stack that
//! produced the accepted reference GGUF (numpy astype casts, PyTorch/MKL exp).
//!
//! Every F16 tensor the remix emits is cast from a BF16-derived f32, so the
//! BF16 bit domain (65536 values) is the complete input space; the unit tests
//! bind `f32_to_f16_bits` exhaustively against `fixtures/bf16_to_f16.bin`
//! (generated by `scripts/gen_numeric_fixtures.py` with the reference venv).

use std::sync::OnceLock;

/// PyTorch 2.13.0+cpu (Intel MKL vmsExp, VML_HA) `exp` over the BF16 domain.
///
/// MKL is closed source and deviates from correctly-rounded exp on 1794 of
/// the 65536 BF16-derived inputs (and quiets NaN payloads differently), so
/// the semantic is embedded as a domain table rather than re-derived from an
/// algorithm. See `scripts/gen_numeric_fixtures.py` for provenance.
static TORCH_EXP_BF16: &[u8; 65536 * 4] = include_bytes!("../fixtures/torch_exp_bf16.bin");

#[inline]
pub fn bf16_to_f32_bits(bits: u16) -> u32 {
    (bits as u32) << 16
}

#[inline]
pub fn bf16_to_f32(bits: u16) -> f32 {
    f32::from_bits(bf16_to_f32_bits(bits))
}

/// `torch.exp` (MKL vmsExp HA) of the f32 value whose bits are `bf16 << 16`.
#[inline]
pub fn torch_exp_bf16_bits(bits: u16) -> u32 {
    let i = bits as usize * 4;
    u32::from_le_bytes([
        TORCH_EXP_BF16[i],
        TORCH_EXP_BF16[i + 1],
        TORCH_EXP_BF16[i + 2],
        TORCH_EXP_BF16[i + 3],
    ])
}

/// IEEE 754 binary32 -> binary16, round-to-nearest-even, overflow to inf,
/// NaN payload MSBs kept (numpy software-cast semantics, bound exhaustively
/// against the numpy fixture by the test below).
pub fn f32_to_f16_bits(x: f32) -> u16 {
    let b = x.to_bits();
    let sign = ((b >> 16) & 0x8000) as u16;
    let exp32 = ((b >> 23) & 0xff) as i32;
    let man = b & 0x007f_ffff;

    if exp32 == 0xff {
        if man == 0 {
            return sign | 0x7c00; // inf
        }
        // NaN: keep payload MSBs; if they vanish, nudge so it stays a NaN
        // (numpy npy_floatbits_to_halfbits semantics -- no quiet-bit forcing).
        let mut ret = 0x7c00 | ((man >> 13) as u16);
        if ret == 0x7c00 {
            ret += 1;
        }
        return sign | ret;
    }

    let e = exp32 - 127 + 15;
    if e >= 0x1f {
        return sign | 0x7c00; // overflow -> inf
    }
    if e <= 0 {
        if e < -10 {
            return sign; // rounds to zero
        }
        // Subnormal: add the implicit bit, shift out (14 - e) bits with RNE.
        let m = man | 0x0080_0000;
        let shift = (14 - e) as u32;
        let half = 1u32 << (shift - 1);
        let rest = m & ((1u32 << shift) - 1);
        let mut h = (m >> shift) as u16;
        if rest > half || (rest == half && (h & 1) == 1) {
            h += 1; // may carry into the exponent; that is correct
        }
        return sign | h;
    }
    // Normal: 13 mantissa bits shifted out with RNE.
    let mut h = ((e as u32) << 10) | (man >> 13);
    let rest = man & 0x1fff;
    if rest > 0x1000 || (rest == 0x1000 && (h & 1) == 1) {
        h += 1; // may carry up to inf; that is correct
    }
    sign | (h as u16)
}

/// BF16 -> F16 (via exact BF16 -> f32 upcast, then the RNE cast above),
/// table-accelerated for bulk tensor casts.
pub fn bf16_to_f16_table() -> &'static [u16; 65536] {
    static TABLE: OnceLock<Box<[u16; 65536]>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut t = vec![0u16; 65536].into_boxed_slice();
        for (bits, out) in t.iter_mut().enumerate() {
            *out = f32_to_f16_bits(bf16_to_f32(bits as u16));
        }
        t.try_into().unwrap()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> Vec<u8> {
        let path = format!("{}/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
        std::fs::read(path).expect("fixture missing; run scripts/gen_numeric_fixtures.py")
    }

    #[test]
    fn f16_cast_matches_numpy_exhaustively_over_bf16_domain() {
        let fx = fixture("bf16_to_f16.bin");
        assert_eq!(fx.len(), 65536 * 2);
        let table = bf16_to_f16_table();
        for bits in 0..=0xffffu32 {
            let expect = u16::from_le_bytes([fx[bits as usize * 2], fx[bits as usize * 2 + 1]]);
            let got = table[bits as usize];
            assert_eq!(
                got,
                expect,
                "bf16 bits {bits:#06x} (f32 {:#010x}): got {got:#06x}, numpy {expect:#06x}",
                bf16_to_f32_bits(bits as u16)
            );
        }
    }

    #[test]
    fn f16_cast_known_values() {
        assert_eq!(f32_to_f16_bits(0.0), 0x0000);
        assert_eq!(f32_to_f16_bits(-0.0), 0x8000);
        assert_eq!(f32_to_f16_bits(1.0), 0x3c00);
        assert_eq!(f32_to_f16_bits(65504.0), 0x7bff);
        assert_eq!(f32_to_f16_bits(65520.0), 0x7c00); // halfway, ties-to-even -> inf
        assert_eq!(f32_to_f16_bits(65519.9), 0x7bff);
        assert_eq!(f32_to_f16_bits(f32::INFINITY), 0x7c00);
        assert_eq!(f32_to_f16_bits(f32::NEG_INFINITY), 0xfc00);
        assert_eq!(f32_to_f16_bits(5.960_464_5e-8), 0x0001); // smallest f16 subnormal
        assert_eq!(f32_to_f16_bits(2.980_232_2e-8), 0x0000); // exactly half of it, ties-to-even
    }

    #[test]
    fn torch_exp_spot_values() {
        // exp(0) = 1, exp(-inf) = 0, exp(inf) = inf.
        assert_eq!(torch_exp_bf16_bits(0x0000), 1.0f32.to_bits());
        assert_eq!(torch_exp_bf16_bits(0xff80), 0.0f32.to_bits()); // -inf
        assert_eq!(torch_exp_bf16_bits(0x7f80), f32::INFINITY.to_bits());
        // Monotone non-decreasing on a finite positive ramp.
        let mut prev = 0.0f32;
        for bits in 0x3f80..0x4280u16 {
            // 1.0 .. 64.0
            let v = f32::from_bits(torch_exp_bf16_bits(bits));
            assert!(v >= prev, "exp not monotone at bf16 {bits:#06x}");
            prev = v;
        }
    }
}
